export const SELECT_INDUSTRIES = [
  { value: "IT", label: "Tecnología" },
  { value: "Marketing", label: "Marketing" },
  { value: "Finanzas", label: "Finanzas" },
  { value: "Salud", label: "Salud" },
  { value: "Educacion", label: "Educación" },
  { value: "Gobierno", label: "Gobierno" },
  { value: "Arquitectura", label: "Arquitectura" },
  { value: "Ingenieria", label: "Ingeniería" },
  { value: "Legal", label: "Legal" },
  { value: "Ventas", label: "Ventas" },
  { value: "RecursosHumanos", label: "RRHH" },
  { value: "Manufactura", label: "Manufactura" },
  { value: "Logistica", label: "Logística" },
  { value: "Construccion", label: "Construcción" },
  { value: "ArteDiseno", label: "Arte y Diseño" },
  { value: "Comunicacion", label: "Comunicación" },
  { value: "Ciencias", label: "Investigación" },
  { value: "Turismo", label: "Turismo" },
  { value: "Gastronomia", label: "Gastronomía" },
  { value: "Energia", label: "Energía" },
  { value: "RecursosNaturales", label: "RRNN" },
  { value: "Agropecuario", label: "Agropecuario" },
  { value: "Retail", label: "Retail" },
  { value: "Startup", label: "Startups" },
];

// Puerto Rico
export const SELECT_LOCATION = [
  { value: "remote", label: "Remoto" },
  { value: "Adjuntas", label: "Adjuntas" },
  { value: "Aguada", label: "Aguada" },
  { value: "Aguadilla", label: "Aguadilla" },
  { value: "Aguas Buenas", label: "Aguas Buenas" },
  { value: "Aibonito", label: "Aibonito" },
  { value: "Anasco", label: "Añasco" },
  { value: "Arecibo", label: "Arecibo" },
  { value: "Arroyo", label: "Arroyo" },
  { value: "Barceloneta", label: "Barceloneta" },
  { value: "Barranquitas", label: "Barranquitas" },
  { value: "Bayamon", label: "Bayamón" },
  { value: "Cabo Rojo", label: "Cabo Rojo" },
  { value: "Caguas", label: "Caguas" },
  { value: "Camuy", label: "Camuy" },
  { value: "Canovanas", label: "Canóvanas" },
  { value: "Carolina", label: "Carolina" },
  { value: "Catano", label: "Cataño" },
  { value: "Cayey", label: "Cayey" },
  { value: "Ceiba", label: "Ceiba" },
  { value: "Ciales", label: "Ciales" },
  { value: "Cidra", label: "Cidra" },
  { value: "Coamo", label: "Coamo" },
  { value: "Comerio", label: "Comerío" },
  { value: "Corozal", label: "Corozal" },
  { value: "Culebra", label: "Culebra" },
  { value: "Dorado", label: "Dorado" },
  { value: "Fajardo", label: "Fajardo" },
  { value: "Florida", label: "Florida" },
  { value: "Guanica", label: "Guánica" },
  { value: "Guayama", label: "Guayama" },
  { value: "Guayanilla", label: "Guayanilla" },
  { value: "Guaynabo", label: "Guaynabo" },
  { value: "Gurabo", label: "Gurabo" },
  { value: "Hatillo", label: "Hatillo" },
  { value: "Hormigueros", label: "Hormigueros" },
  { value: "Humacao", label: "Humacao" },
  { value: "Isabela", label: "Isabela" },
  { value: "Jayuya", label: "Jayuya" },
  { value: "Juana Diaz", label: "Juana Díaz" },
  { value: "Juncos", label: "Juncos" },
  { value: "Lajas", label: "Lajas" },
  { value: "Lares", label: "Lares" },
  { value: "Las Marias", label: "Las Marías" },
  { value: "Las Piedras", label: "Las Piedras" },
  { value: "Loiza", label: "Loíza" },
  { value: "Luquillo", label: "Luquillo" },
  { value: "Manati", label: "Manatí" },
  { value: "Maricao", label: "Maricao" },
  { value: "Maunabo", label: "Maunabo" },
  { value: "Mayaguez", label: "Mayagüez" },
  { value: "Moca", label: "Moca" },
  { value: "Morovis", label: "Morovis" },
  { value: "Naguabo", label: "Naguabo" },
  { value: "Naranjito", label: "Naranjito" },
  { value: "Orocovis", label: "Orocovis" },
  { value: "Patillas", label: "Patillas" },
  { value: "Penuelas", label: "Peñuelas" },
  { value: "Ponce", label: "Ponce" },
  { value: "Quebradillas", label: "Quebradillas" },
  { value: "Rincon", label: "Rincón" },
  { value: "Rio Grande", label: "Río Grande" },
  { value: "Sabana Grande", label: "Sabana Grande" },
  { value: "Salinas", label: "Salinas" },
  { value: "San German", label: "San Germán" },
  { value: "San Juan", label: "San Juan" },
  { value: "San Lorenzo", label: "San Lorenzo" },
  { value: "San Sebastian", label: "San Sebastián" },
  { value: "Santa Isabel", label: "Santa Isabel" },
  { value: "Toa Alta", label: "Toa Alta" },
  { value: "Toa Baja", label: "Toa Baja" },
  { value: "Trujillo Alto", label: "Trujillo Alto" },
  { value: "Utuado", label: "Utuado" },
  { value: "Vega Alta", label: "Vega Alta" },
  { value: "Vega Baja", label: "Vega Baja" },
  { value: "Vieques", label: "Vieques" },
  { value: "Villalba", label: "Villalba" },
  { value: "Yabucoa", label: "Yabucoa" },
  { value: "Yauco", label: "Yauco" },
];

export const SELECT_EMPLOYMENT = [
  { value: "full-time", label: "Full-time" },
  { value: "part-time", label: "Part-time" },
  { value: "contract", label: "Contract" },
  { value: "remote", label: "Remote" },
];

export const REGIONAL_OFFICE = [
  {
    value: "barceloneta",
    label: "Barceloneta",
  },
  {
    value: "santurce",
    label: "Santurce",
  },
  {
    value: "las-piedras",
    label: "Las Piedras",
  },
  {
    value: "san-german",
    label: "San Germán",
  },
  {
    value: "salinas",
    label: "Salinas",
  },
];

export const SELECT_FREQUENCY_PAYMENT = [
  { value: "semanal", label: "Semanal" },
  { value: "mensual", label: "Mensual" },
  { value: "anual", label: "Anual" },
  { value: "diario", label: "Diario" },
  { value: "hora", label: "Hora" },
];
